name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 22
            - name: Install dependencies
              run: npm install
            - name: Lint files
              run: npm run lint
              continue-on-error: true
            - name: Try making builds
              run: npm run build

